<!DOCTYPE html>
<html lang="pt">
    <head>
        <meta charset=utf-8>
        <title>Mailing<?= isset($this->titulo) ? ' - ' . $this->titulo : null ?></title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="keywords" content="">
        <meta name="description" content="">
        <meta name="robots" content="ALL">
        <meta name="distribution" content="Global">
        <meta name="rating" content="General">
        <meta name="author" content="">
        <meta name="language" content="pt-br">
        <meta name="doc-class" content="Completed">
        <meta name="doc-rights" content="Protected">

        <link href="<?= $this->baseUrl('/img/favicon.ico') ?>" rel="icon" type="image/x-icon">

        <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl('/js/twitter-bootstrap/docs/assets/css/bootstrap.css') ?>"/>
        <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl('/js/twitter-bootstrap/docs/assets/css/docs.css') ?>"/>
        <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl('/css/admin.css') ?>"/>

        <script src="<?= $this->baseUrl('/js/lib/jquery-1.7.2.min.js') ?>"></script>
        <script src="<?= $this->baseUrl('/js/twitter-bootstrap/js/bootstrap-dropdown.js') ?>"></script>
        <script src="<?= $this->baseUrl('/js/twitter-bootstrap/js/bootstrap-modal.js') ?>"></script>
        <script src="<?= $this->baseUrl('/js/lib/admin.js') ?>"></script>
    </head>
    <body>
        <section id="navbar">
            <!--div class="page-header">
                <h1>Mailing</h1>
            </div-->
            <div class="navbar">
                <div class="navbar-inner">
                    <div class="container" style="width: auto;">
                        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </a>
                        <a class="brand" href="<?= $this->baseUrl('/') ?>"><?= (isset(Zend_Registry::get('Zend_Session')->empresa) ? Zend_Registry::get('Zend_Session')->empresa->str_nome : null); ?></a>
                        <?php if (isset(Zend_Registry::get('Zend_Session')->usuario)): ?>
                        <div class="nav-collapse">
                            <ul class="nav">
                                <li class="active"><a href="<?= $this->baseUrl('/admin/index') ?>">Início</a></li>
                                <?php if (Zend_Registry::get('Zend_Session')->usuario->id_usuario_nivel == 1): ?>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Empresas <b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li><a href="<?= $this->baseUrl('/admin/empresas/') ?>">Listar</a></li>
                                        <li><a href="<?= $this->baseUrl('/admin/empresas/editar') ?>">Cadastrar</a></li>
                                    </ul>
                                </li>
                                <?php endif; ?>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Campanhas <b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li><a href="<?= $this->baseUrl('/admin/campanhas/') ?>">Listar</a></li>
                                        <li><a href="<?= $this->baseUrl('/admin/campanhas/editar') ?>">Cadastrar</a></li>
                                    </ul>
                                </li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Contatos <b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li><a href="<?= $this->baseUrl('/admin/grupos/') ?>">Grupos</a></li>
                                        <li><a href="<?= $this->baseUrl('/admin/grupos/editar') ?>">Inserir</a></li>
                                        <li class="divider"></li>
                                        <li><a href="<?= $this->baseUrl('/admin/emails/') ?>">Contatos</a></li>
                                        <li><a href="<?= $this->baseUrl('/admin/emails/editar') ?>">Inserir</a></li>
                                        <li class="divider"></li>
                                        <li><a href="<?= $this->baseUrl('/admin/emails/upload') ?>">Importar</a></li>
                                    </ul>
                                </li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Templates <b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li><a href="<?= $this->baseUrl('/admin/templates') ?>">Listar</a></li>
                                        <li><a href="<?= $this->baseUrl('/admin/templates/editar') ?>">Criar</a></li>
                                    </ul>
                                </li>
                                <?php if (Zend_Registry::get('Zend_Session')->usuario->id_usuario_nivel <= 2): ?>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Usuários <b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li><a href="<?= $this->baseUrl('/admin/usuarios') ?>">Listar</a></li>
                                        <li><a href="<?= $this->baseUrl('/admin/usuarios/editar') ?>">Cadastrar</a></li>
                                    </ul>
                                </li>
                                <?php endif; ?>
                            </ul>
                            <ul class="nav pull-right">
                                <li class="divider-vertical"></li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?= Zend_Registry::get('Zend_Session')->usuario->str_email ?> <b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li><a href="<?= $this->baseUrl('/admin/perfil/senha') ?>">Trocar senha</a></li>
                                        <li><a href="<?= $this->baseUrl('/admin/perfil/email') ?>">Trocar e-mail</a></li>
                                        <li class="divider"></li>
                                        <li><a href="<?= $this->baseUrl('/admin/acesso/logout') ?>">Sair</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div><!-- /.nav-collapse -->
                        <?php endif; ?>
                    </div>
                </div><!-- /navbar-inner -->
            </div><!-- /navbar -->
        </section>
        <div class="container">
            <?= $this->mensagem(); ?>
            <?= $this->layout()->content; ?>
        </div>
    </body>
</html>
