<div id="admin-campanhas-criar">
    <h2 class="span12 offset0">Campanha</h2>

    <?= $this->form ?>
</div>
<script src="/js/jquery-validation-1.9.0/jquery.validate.min.js"></script>
<script src="/js/jquery-maskedinput/jquery.maskedinput-1.2.2.min.js"></script>
<script src="/js/ckeditor/ckeditor.js"></script>
<script src="/js/ckeditor/adapters/jquery.js"></script>
<script src="/js/lib/admin_campanhas.js"></script>